{% set name = "vector" %}
{% set version = "0.8.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vector-{{ version }}.tar.gz
  sha256: 601b64510d84ddd0f44390e21c93d06bc08df2d88b85203379726b594d4cfa4b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools-scm
  run:
    - numpy >=1.13.3
    - python >=3.6
    - importlib_metadata >=0.22
    - typing-extensions
    - packaging

test:
  imports:
    - vector
    - vector._backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/vector
  summary: Vector classes and utilities
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - conda-forge/scikit-hep
